# Workflow template for oss-wishlist/wishlists repository
# Copy this to: .github/workflows/manage-wishlist-actions.yml

name: Manage Wishlist Actions

on:
  # Triggered by your app via webhook when a wishlist is approved
  repository_dispatch:
    types: [wishlist-approved]
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      wishlist_id:
        description: 'Wishlist ID to process'
        required: true
        type: number

jobs:
  manage-wishlist:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read       # To read repository content
      
    steps:
      - name: Manage Wishlist Actions
        uses: oss-wishlist/manage-wishlist-actions@v1.1.1
        with:
          # IMPORTANT: Use a PAT with 'public_repo' scope stored in secrets
          # The default GITHUB_TOKEN cannot create PRs in other repositories
          github-token: ${{ secrets.WISHLIST_BOT_TOKEN }}
          # PostgreSQL connection string for wishlists database
          database-url: ${{ secrets.DATABASE_URL }}
          # Wishlist ID comes from webhook payload or manual input
          wishlist-id: ${{ github.event.client_payload.wishlist_id || github.event.inputs.wishlist_id }}
          # Optional: URL to refresh wishlist cache after PR creation
          cache-url: 'https://urchin-app-bozjb.ondigitalocean.app/api/wishlists?refresh=true'
